FROM arrow-builder:latest
#FROM quay.io/tchughesiv/arrow-builder:17.0.0

RUN ls -la
RUN yum install -y rust cargo

USER 1001

RUN git clone -b 9.5.0 https://github.com/ibis-project/ibis
RUN git clone --branch v2.4.12 --recurse-submodules https://github.com/milvus/milvus-lite
#RUN git clone --branch v2.4.12-fixes --recurse-submodules https://github.com/tchughesiv/milvus-lite

RUN pip install pydantic_core==2.27.2 watchfiles==1.0.4 conan
RUN pip list
