FROM registry.access.redhat.com/ubi8/python-311:1

USER 0
RUN npm install -g yarn yalc && rm -rf .npm
USER default

COPY --chown=default ui ${APP_ROOT}/src/ui
WORKDIR ${APP_ROOT}/src/ui
RUN npm install && \
    npm run build:lib-dev && \
    rm -rf node_modules && \
    npm cache clean --force

COPY --chown=default .git ${APP_ROOT}/src/.git
COPY --chown=default protos ${APP_ROOT}/src/protos
COPY --chown=default setup.py pyproject.toml README.md Makefile ${APP_ROOT}/src/
COPY --chown=default sdk/python ${APP_ROOT}/src/sdk/python
WORKDIR ${APP_ROOT}/src/sdk/python/feast/ui
RUN yalc add @feast-dev/feast-ui && \
    git diff package.json && \
    yarn install && \
    npm run build --omit=dev && \
    rm -rf node_modules && \
    npm cache clean --force && \
    yarn cache clean --all

WORKDIR ${APP_ROOT}/src
RUN pip install -r sdk/python/requirements/py3.11-ci-requirements.txt && \
    pip install --no-deps .[aws,gcp,snowflake,redis,go,mysql,postgres,opentelemetry,grpcio,k8s,duckdb,milvus]
    # pip install --no-cache-dir pip-tools && \
    # make install-python-ci-dependencies && \
    # pip uninstall -y pip-tools

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json
