resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/tchughesiv/feast-operator
  newTag: e040b18538c58ed3418ebb9d40313056fd2b3326
