apiVersion: v1
kind: Secret
metadata:
  name: feast-postgresql
stringData:
  postgres: |
    host: postgres.feast.svc.cluster.local
    port: 5432
    database: feast
    db_schema: public
    user: feast
    password: feast
  sql: |
    path: postgresql+psycopg://feast:feast@postgres.feast.svc.cluster.local:5432/feast
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: example
spec:
  feastProject: sample
  services:
    offlineStore:
      image: 'quay.io/tchughesiv/feature-server:0.41.0-dev'
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-postgresql
      tls:
        disable: true
    onlineStore:
      image: 'quay.io/tchughesiv/feature-server:0.41.0-dev'
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-postgresql
      tls:
        disable: true
    registry:
      local:
        image: 'quay.io/tchughesiv/feature-server:0.41.0-dev'
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-postgresql
        tls:
          disable: true
